#[derive(Debug, Clone, Copy)]
pub(crate) enum Inst {
    Add,
    Call(u8),
    Class(u8),
    CloseUpVal,
    Closure(u8),
    Const(u8),
    DefGlobal(u8),
    Div,
    Equal,
    False,
    GetGlobal(u8),
    GetLocal(u8),
    GetProp(u8),
    GetSuper(u8),
    GetUpVal(u8),
    Greater,
    Inherit,
    Invoke(u8, u8),
    JumpIf(u16),
    JumpUnless(u16),
    Less,
    Loop(u16),
    Method(u8),
    Mul,
    Neg,
    Nil,
    Not,
    Pop,
    Print,
    Return,
    SetGlobal(u8),
    SetLocal(u8),
    SetProp(u8),
    SetUpVal(u8),
    Sub,
    SuperInvoke(u8, u8),
    True,
}
