name: Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - run: apt-get update && apt-get install -y curl build-essential
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Test native build
        run: cargo build --verbose
      - name: Run simple tests
        run: cargo test --verbose
      - name: Run heavy tests
        run: cargo test --verbose -- --ignored
